export const places = [
  {
    count: 54513,
    path: 'Paris',
    state: 'displayed',
    name: 'Paris',
  },
  {
    count: 47423,
    path: 'London',
    state: 'displayed',
    name: 'London',
  },
  {
    count: 20454,
    path: 'Berlin',
    state: 'displayed',
    name: 'Berlin',
  },
  {
    count: 19528,
    path: 'New York',
    state: 'displayed',
    name: 'New York',
  },
  {
    count: 19426,
    path: 'Los Angeles',
    state: 'displayed',
    name: 'Los Angeles',
  },
  {
    count: 18618,
    path: 'Roma',
    state: 'displayed',
    name: 'Roma',
  },
  {
    count: 17431,
    path: 'Barcelona',
    state: 'displayed',
    name: 'Barcelona',
  },
  {
    count: 16419,
    path: 'Brooklyn',
    state: 'displayed',
    name: 'Brooklyn',
  },
  {
    count: 14869,
    path: 'Amsterdam',
    state: 'displayed',
    name: 'Amsterdam',
  },
  {
    count: 13805,
    path: 'K\u00f8benhavn',
    state: 'displayed',
    name: 'K\u00f8benhavn',
  },
  {
    count: 13207,
    path: 'Madrid',
    state: 'displayed',
    name: 'Madrid',
  },
  {
    count: 12624,
    path: 'Toronto',
    state: 'displayed',
    name: 'Toronto',
  },
  {
    count: 9563,
    path: 'Austin',
    state: 'displayed',
    name: 'Austin',
  },
  {
    count: 8680,
    path: 'San Francisco',
    state: 'displayed',
    name: 'San Francisco',
  },
  {
    count: 7692,
    path: 'Washington',
    state: 'displayed',
    name: 'Washington',
  },
  {
    count: 7659,
    path: 'Montr\u00e9al',
    state: 'displayed',
    name: 'Montr\u00e9al',
  },
  {
    count: 6201,
    path: 'San Diego',
    state: 'displayed',
    name: 'San Diego',
  },
  {
    count: 6130,
    path: 'Edinburgh',
    state: 'displayed',
    name: 'Edinburgh',
  },
  {
    count: 6121,
    path: 'Wien',
    state: 'displayed',
    name: 'Wien',
  },
  {
    count: 6064,
    path: 'Rome',
    state: 'displayed',
    name: 'Rome',
  },
  {
    count: 5532,
    path: 'Vancouver',
    state: 'displayed',
    name: 'Vancouver',
  },
  {
    count: 5293,
    path: 'New Orleans',
    state: 'displayed',
    name: 'New Orleans',
  },
  {
    count: 5186,
    path: 'Chicago',
    state: 'displayed',
    name: 'Chicago',
  },
  {
    count: 4263,
    path: 'Dublin',
    state: 'displayed',
    name: 'Dublin',
  },
  {
    count: 4067,
    path: 'Venezia',
    state: 'displayed',
    name: 'Venezia',
  },
  {
    count: 3859,
    path: 'Hong Kong',
    state: 'displayed',
    name: 'Hong Kong',
  },
  {
    count: 3812,
    path: 'Seattle',
    state: 'displayed',
    name: 'Seattle',
  },
  {
    count: 3560,
    path: 'Athina',
    state: 'displayed',
    name: 'Athina',
  },
  {
    count: 3539,
    path: 'Portland',
    state: 'displayed',
    name: 'Portland',
  },
  {
    count: 3382,
    path: 'Boston',
    state: 'displayed',
    name: 'Boston',
  },
  {
    count: 3326,
    path: 'Copenhagen',
    state: 'displayed',
    name: 'Copenhagen',
  },
  {
    count: 3212,
    path: 'Nashville',
    state: 'displayed',
    name: 'Nashville',
  },
  {
    count: 2670,
    path: 'Montreal',
    state: 'displayed',
    name: 'Montreal',
  },
  {
    count: 2670,
    path: 'Queens',
    state: 'displayed',
    name: 'Queens',
  },
  {
    count: 2497,
    path: 'Denver',
    state: 'displayed',
    name: 'Denver',
  },
  {
    count: 2391,
    path: 'Frederiksberg',
    state: 'displayed',
    name: 'Frederiksberg',
  },
  {
    count: 2097,
    path: 'Melbourne',
    state: 'displayed',
    name: 'Melbourne',
  },
  {
    count: 1994,
    path: 'Palma',
    state: 'displayed',
    name: 'Palma',
  },
  {
    count: 1937,
    path: 'Venice',
    state: 'displayed',
    name: 'Venice',
  },
  {
    count: 1670,
    path: 'Vienna',
    state: 'displayed',
    name: 'Vienna',
  },
  {
    count: 1609,
    path: 'Oakland',
    state: 'displayed',
    name: 'Oakland',
  },
  {
    count: 1502,
    path: 'Bondi Beach',
    state: 'displayed',
    name: 'Bondi Beach',
  },
  {
    count: 1429,
    path: 'Gen\u00e8ve',
    state: 'displayed',
    name: 'Gen\u00e8ve',
  },
  {
    count: 1245,
    path: 'Bruxelles',
    state: 'displayed',
    name: 'Bruxelles',
  },
  {
    count: 1183,
    path: 'Ville de Qu\u00e9bec',
    state: 'displayed',
    name: 'Ville de Qu\u00e9bec',
  },
  {
    count: 1077,
    path: 'Long Beach',
    state: 'displayed',
    name: 'Long Beach',
  },
  {
    count: 1041,
    path: 'Athens',
    state: 'displayed',
    name: 'Athens',
  },
  {
    count: 1026,
    path: 'Antwerpen',
    state: 'displayed',
    name: 'Antwerpen',
  },
  {
    count: 1016,
    path: 'Ixelles',
    state: 'displayed',
    name: 'Ixelles',
  },
  {
    count: 992,
    path: 'Santa Monica',
    state: 'displayed',
    name: 'Santa Monica',
  },
  {
    count: 991,
    path: 'Pollen\u00e7a',
    state: 'displayed',
    name: 'Pollen\u00e7a',
  },
  {
    count: 939,
    path: 'West Hollywood',
    state: 'displayed',
    name: 'West Hollywood',
  },
  {
    count: 914,
    path: 'Manly',
    state: 'displayed',
    name: 'Manly',
  },
  {
    count: 862,
    path: 'Alc\u00fadia',
    state: 'displayed',
    name: 'Alc\u00fadia',
  },
  {
    count: 850,
    path: 'Greater London',
    state: 'displayed',
    name: 'Greater London',
  },
  {
    count: 810,
    path: 'Manchester',
    state: 'displayed',
    name: 'Manchester',
  },
  {
    count: 800,
    path: 'Surry Hills',
    state: 'displayed',
    name: 'Surry Hills',
  },
  {
    count: 728,
    path: 'Palma de Mallorca',
    state: 'displayed',
    name: 'Palma de Mallorca',
  },
  {
    count: 725,
    path: 'Bondi',
    state: 'displayed',
    name: 'Bondi',
  },
  {
    count: 689,
    path: 'Richmond',
    state: 'displayed',
    name: 'Richmond',
  },
  {
    count: 672,
    path: 'Coogee',
    state: 'displayed',
    name: 'Coogee',
  },
  {
    count: 654,
    path: 'Saint-Gilles',
    state: 'displayed',
    name: 'Saint-Gilles',
  },
  {
    count: 631,
    path: 'Southbank',
    state: 'displayed',
    name: 'Southbank',
  },
  {
    count: 614,
    path: 'Bronx',
    state: 'displayed',
    name: 'Bronx',
  },
  {
    count: 598,
    path: 'Sydney',
    state: 'displayed',
    name: 'Sydney',
  },
  {
    count: 593,
    path: 'South Yarra',
    state: 'displayed',
    name: 'South Yarra',
  },
  {
    count: 588,
    path: 'Darlinghurst',
    state: 'displayed',
    name: 'Darlinghurst',
  },
  {
    count: 588,
    path: 'North Bondi',
    state: 'displayed',
    name: 'North Bondi',
  },
  {
    count: 588,
    path: 'Pasadena',
    state: 'displayed',
    name: 'Pasadena',
  },
  {
    count: 570,
    path: 'Randwick',
    state: 'displayed',
    name: 'Randwick',
  },
  {
    count: 529,
    path: 'Saint Kilda',
    state: 'displayed',
    name: 'Saint Kilda',
  },
  {
    count: 514,
    path: 'Marina del Rey',
    state: 'displayed',
    name: 'Marina del Rey',
  },
  {
    count: 504,
    path: 'Beverly Hills',
    state: 'displayed',
    name: 'Beverly Hills',
  },
  {
    count: 504,
    path: 'Byron Bay',
    state: 'displayed',
    name: 'Byron Bay',
  },
  {
    count: 475,
    path: 'Paddington',
    state: 'displayed',
    name: 'Paddington',
  },
  {
    count: 451,
    path: 'Santa Cruz',
    state: 'displayed',
    name: 'Santa Cruz',
  },
  {
    count: 443,
    path: 'Newtown',
    state: 'displayed',
    name: 'Newtown',
  },
  {
    count: 439,
    path: 'Redfern',
    state: 'displayed',
    name: 'Redfern',
  },
  {
    count: 434,
    path: 'Malibu',
    state: 'displayed',
    name: 'Malibu',
  },
  {
    count: 431,
    path: 'Geneva',
    state: 'displayed',
    name: 'Geneva',
  },
  {
    count: 423,
    path: 'Qu\u00e9bec',
    state: 'displayed',
    name: 'Qu\u00e9bec',
  },
  {
    count: 397,
    path: 'Brussels',
    state: 'displayed',
    name: 'Brussels',
  },
  {
    count: 380,
    path: 'Schaerbeek',
    state: 'displayed',
    name: 'Schaerbeek',
  },
  {
    count: 371,
    path: 'Mosman',
    state: 'displayed',
    name: 'Mosman',
  },
  {
    count: 365,
    path: 'Maroubra',
    state: 'displayed',
    name: 'Maroubra',
  },
  {
    count: 363,
    path: 'Bondi Junction',
    state: 'displayed',
    name: 'Bondi Junction',
  },
  {
    count: 363,
    path: 'Llucmajor',
    state: 'displayed',
    name: 'Llucmajor',
  },
  {
    count: 348,
    path: 'Etterbeek',
    state: 'displayed',
    name: 'Etterbeek',
  },
  {
    count: 344,
    path: 'Rowland Heights',
    state: 'displayed',
    name: 'Rowland Heights',
  },
  {
    count: 341,
    path: 'Bronte',
    state: 'displayed',
    name: 'Bronte',
  },
  {
    count: 339,
    path: '\u0391\u03b8\u03ae\u03bd\u03b1',
    state: 'displayed',
    name: '\u0391\u03b8\u03ae\u03bd\u03b1',
  },
  {
    count: 327,
    path: 'Potts Point',
    state: 'displayed',
    name: 'Potts Point',
  },
  {
    count: 326,
    path: 'Fitzroy',
    state: 'displayed',
    name: 'Fitzroy',
  },
  {
    count: 323,
    path: 'Carlton',
    state: 'displayed',
    name: 'Carlton',
  },
  {
    count: 317,
    path: 'Brunswick',
    state: 'displayed',
    name: 'Brunswick',
  },
  {
    count: 317,
    path: 'Glendale',
    state: 'displayed',
    name: 'Glendale',
  },
  {
    count: 312,
    path: 'Redondo Beach',
    state: 'displayed',
    name: 'Redondo Beach',
  },
  {
    count: 285,
    path: 'Elwood',
    state: 'displayed',
    name: 'Elwood',
  },
  {
    count: 279,
    path: 'Suffolk Park',
    state: 'displayed',
    name: 'Suffolk Park',
  },
  {
    count: 275,
    path: 'Forest',
    state: 'displayed',
    name: 'Forest',
  },
  {
    count: 272,
    path: 'Manacor',
    state: 'displayed',
    name: 'Manacor',
  },
  {
    count: 270,
    path: 'Campos',
    state: 'displayed',
    name: 'Campos',
  },
  {
    count: 266,
    path: 'Can Picafort',
    state: 'displayed',
    name: 'Can Picafort',
  },
  {
    count: 263,
    path: 'Burbank',
    state: 'displayed',
    name: 'Burbank',
  },
  {
    count: 259,
    path: 'Croydon',
    state: 'displayed',
    name: 'Croydon',
  },
  {
    count: 259,
    path: 'Kensington',
    state: 'displayed',
    name: 'Kensington',
  },
  {
    count: 259,
    path: 'Santany\u00ed',
    state: 'displayed',
    name: 'Santany\u00ed',
  },
  {
    count: 255,
    path: 'Culver City',
    state: 'displayed',
    name: 'Culver City',
  },
  {
    count: 255,
    path: 'Twickenham',
    state: 'displayed',
    name: 'Twickenham',
  },
  {
    count: 251,
    path: 'Pyrmont',
    state: 'displayed',
    name: 'Pyrmont',
  },
  {
    count: 250,
    path: 'S\u00f3ller',
    state: 'displayed',
    name: 'S\u00f3ller',
  },
  {
    count: 249,
    path: 'Docklands',
    state: 'displayed',
    name: 'Docklands',
  },
  {
    count: 249,
    path: 'Waterloo',
    state: 'displayed',
    name: 'Waterloo',
  },
  {
    count: 248,
    path: 'Staten Island',
    state: 'displayed',
    name: 'Staten Island',
  },
  {
    count: 246,
    path: 'Bellevue Hill',
    state: 'displayed',
    name: 'Bellevue Hill',
  },
  {
    count: 246,
    path: 'Muro',
    state: 'displayed',
    name: 'Muro',
  },
  {
    count: 245,
    path: 'Uccle',
    state: 'displayed',
    name: 'Uccle',
  },
  {
    count: 241,
    path: 'Arcadia',
    state: 'displayed',
    name: 'Arcadia',
  },
  {
    count: 240,
    path: 'St Kilda',
    state: 'displayed',
    name: 'St Kilda',
  },
  {
    count: 238,
    path: 'North Melbourne',
    state: 'displayed',
    name: 'North Melbourne',
  },
  {
    count: 232,
    path: 'Felanitx',
    state: 'displayed',
    name: 'Felanitx',
  },
  {
    count: 227,
    path: 'Dee Why',
    state: 'displayed',
    name: 'Dee Why',
  },
  {
    count: 222,
    path: 'Glebe',
    state: 'displayed',
    name: 'Glebe',
  },
  {
    count: 222,
    path: 'Rose Bay',
    state: 'displayed',
    name: 'Rose Bay',
  },
  {
    count: 219,
    path: 'Brussel',
    state: 'displayed',
    name: 'Brussel',
  },
  {
    count: 211,
    path: 'Astoria',
    state: 'displayed',
    name: 'Astoria',
  },
  {
    count: 208,
    path: 'Camperdown',
    state: 'displayed',
    name: 'Camperdown',
  },
  {
    count: 205,
    path: 'Northcote',
    state: 'displayed',
    name: 'Northcote',
  },
  {
    count: 205,
    path: 'Prahran',
    state: 'displayed',
    name: 'Prahran',
  },
  {
    count: 205,
    path: '\u9999\u6e2f',
    state: 'displayed',
    name: '\u9999\u6e2f',
  },
  {
    count: 204,
    path: 'Port Melbourne',
    state: 'displayed',
    name: 'Port Melbourne',
  },
  {
    count: 202,
    path: 'Inca',
    state: 'displayed',
    name: 'Inca',
  },
  {
    count: 201,
    path: 'Fitzroy North',
    state: 'displayed',
    name: 'Fitzroy North',
  },
  {
    count: 198,
    path: 'Amsterdam-Zuidoost',
    state: 'displayed',
    name: 'Amsterdam-Zuidoost',
  },
  {
    count: 198,
    path: 'Lido',
    state: 'displayed',
    name: 'Lido',
  },
  {
    count: 198,
    path: 'Sa Pobla',
    state: 'displayed',
    name: 'Sa Pobla',
  },
  {
    count: 193,
    path: 'Antwerp',
    state: 'displayed',
    name: 'Antwerp',
  },
  {
    count: 193,
    path: 'Erskineville',
    state: 'displayed',
    name: 'Erskineville',
  },
  {
    count: 193,
    path: 'Londres',
    state: 'displayed',
    name: 'Londres',
  },
  {
    count: 192,
    path: 'Illes Balears',
    state: 'displayed',
    name: 'Illes Balears',
  },
  {
    count: 192,
    path: 'South Melbourne',
    state: 'displayed',
    name: 'South Melbourne',
  },
  {
    count: 190,
    path: 'Manhattan Beach',
    state: 'displayed',
    name: 'Manhattan Beach',
  },
  {
    count: 189,
    path: 'Lido di Ostia',
    state: 'displayed',
    name: 'Lido di Ostia',
  },
  {
    count: 188,
    path: 'Clovelly',
    state: 'displayed',
    name: 'Clovelly',
  },
  {
    count: 188,
    path: 'Freshwater',
    state: 'displayed',
    name: 'Freshwater',
  },
  {
    count: 187,
    path: 'Harrow',
    state: 'displayed',
    name: 'Harrow',
  },
  {
    count: 186,
    path: 'Anderlecht',
    state: 'displayed',
    name: 'Anderlecht',
  },
  {
    count: 186,
    path: 'Collingwood',
    state: 'displayed',
    name: 'Collingwood',
  },
  {
    count: 186,
    path: 'Newport',
    state: 'displayed',
    name: 'Newport',
  },
  {
    count: 186,
    path: 'Woollahra',
    state: 'displayed',
    name: 'Woollahra',
  },
  {
    count: 181,
    path: 'Alexandria',
    state: 'displayed',
    name: 'Alexandria',
  },
  {
    count: 180,
    path: 'Avalon Beach',
    state: 'displayed',
    name: 'Avalon Beach',
  },
  {
    count: 180,
    path: 'Topanga',
    state: 'displayed',
    name: 'Topanga',
  },
  {
    count: 179,
    path: 'Cremorne',
    state: 'displayed',
    name: 'Cremorne',
  },
  {
    count: 179,
    path: 'Elizabeth Bay',
    state: 'displayed',
    name: 'Elizabeth Bay',
  },
  {
    count: 178,
    path: 'Brunswick East',
    state: 'displayed',
    name: 'Brunswick East',
  },
  {
    count: 178,
    path: 'Chippendale',
    state: 'displayed',
    name: 'Chippendale',
  },
  {
    count: 178,
    path: 'Edgware',
    state: 'displayed',
    name: 'Edgware',
  },
  {
    count: 178,
    path: 'Inglewood',
    state: 'displayed',
    name: 'Inglewood',
  },
  {
    count: 177,
    path: 'Marrickville',
    state: 'displayed',
    name: 'Marrickville',
  },
  {
    count: 176,
    path: 'Col\u00f2nia de Sant Jordi',
    state: 'displayed',
    name: 'Col\u00f2nia de Sant Jordi',
  },
  {
    count: 175,
    path: 'Ultimo',
    state: 'displayed',
    name: 'Ultimo',
  },
  {
    count: 172,
    path: 'Wembley',
    state: 'displayed',
    name: 'Wembley',
  },
  {
    count: 171,
    path: 'Ilford',
    state: 'displayed',
    name: 'Ilford',
  },
  {
    count: 167,
    path: 'Neutral Bay',
    state: 'displayed',
    name: 'Neutral Bay',
  },
  {
    count: 166,
    path: 'Fairlight',
    state: 'displayed',
    name: 'Fairlight',
  },
  {
    count: 166,
    path: 'Kingston upon Thames',
    state: 'displayed',
    name: 'Kingston upon Thames',
  },
  {
    count: 165,
    path: 'Andratx',
    state: 'displayed',
    name: 'Andratx',
  },
  {
    count: 162,
    path: 'Balmain',
    state: 'displayed',
    name: 'Balmain',
  },
  {
    count: 162,
    path: 'North Sydney',
    state: 'displayed',
    name: 'North Sydney',
  },
  {
    count: 161,
    path: 'Abbotsford',
    state: 'displayed',
    name: 'Abbotsford',
  },
  {
    count: 161,
    path: 'Torrance',
    state: 'displayed',
    name: 'Torrance',
  },
  {
    count: 159,
    path: 'Alcudia',
    state: 'displayed',
    name: 'Alcudia',
  },
  {
    count: 159,
    path: 'Altadena',
    state: 'displayed',
    name: 'Altadena',
  },
  {
    count: 155,
    path: 'Calvi\u00e0',
    state: 'displayed',
    name: 'Calvi\u00e0',
  },
  {
    count: 152,
    path: 'Ballsbridge',
    state: 'displayed',
    name: 'Ballsbridge',
  },
  {
    count: 150,
    path: 'Alhambra',
    state: 'displayed',
    name: 'Alhambra',
  },
  {
    count: 147,
    path: 'Saint-Josse-ten-Noode',
    state: 'displayed',
    name: 'Saint-Josse-ten-Noode',
  },
  {
    count: 147,
    path: 'San Gabriel',
    state: 'displayed',
    name: 'San Gabriel',
  },
  {
    count: 147,
    path: 'Tamarama',
    state: 'displayed',
    name: 'Tamarama',
  },
  {
    count: 146,
    path: 'Zetland',
    state: 'displayed',
    name: 'Zetland',
  },
  {
    count: 145,
    path: 'La Jolla',
    state: 'displayed',
    name: 'La Jolla',
  },
  {
    count: 144,
    path: 'Quebec',
    state: 'displayed',
    name: 'Quebec',
  },
  {
    count: 141,
    path: 'Vaucluse',
    state: 'displayed',
    name: 'Vaucluse',
  },
  {
    count: 140,
    path: 'Waverley',
    state: 'displayed',
    name: 'Waverley',
  },
  {
    count: 137,
    path: 'Bromley',
    state: 'displayed',
    name: 'Bromley',
  },
  {
    count: 137,
    path: 'Hermosa Beach',
    state: 'displayed',
    name: 'Hermosa Beach',
  },
  {
    count: 137,
    path: 'Hong Kong Island',
    state: 'displayed',
    name: 'Hong Kong Island',
  },
  {
    count: 136,
    path: 'East Melbourne',
    state: 'displayed',
    name: 'East Melbourne',
  },
  {
    count: 133,
    path: 'Double Bay',
    state: 'displayed',
    name: 'Double Bay',
  },
  {
    count: 133,
    path: 'Rathmines',
    state: 'displayed',
    name: 'Rathmines',
  },
  {
    count: 133,
    path: 'Rushcutters Bay',
    state: 'displayed',
    name: 'Rushcutters Bay',
  },
  {
    count: 132,
    path: 'Capdepera',
    state: 'displayed',
    name: 'Capdepera',
  },
  {
    count: 132,
    path: 'Monterey Park',
    state: 'displayed',
    name: 'Monterey Park',
  },
  {
    count: 131,
    path: 'Queenscliff',
    state: 'displayed',
    name: 'Queenscliff',
  },
  {
    count: 131,
    path: 'Trento',
    state: 'displayed',
    name: 'Trento',
  },
  {
    count: 131,
    path: 'Tsim Sha Tsui',
    state: 'displayed',
    name: 'Tsim Sha Tsui',
  },
  {
    count: 130,
    path: 'Annandale',
    state: 'displayed',
    name: 'Annandale',
  },
  {
    count: 313707,
    path: 'Entire home/apt',
    state: 'displayed',
    name: 'Entire home/apt',
  },
  {
    count: 172306,
    path: 'Private room',
    state: 'displayed',
    name: 'Private room',
  },
  {
    count: 8939,
    path: 'Shared room',
    state: 'displayed',
    name: 'Shared room',
  },
  {
    count: 1,
    path: '9',
    state: 'displayed',
    name: '9',
  },
  {
    count: 134545,
    path: 'United States',
    state: 'displayed',
    name: 'United States',
  },
  {
    count: 61041,
    path: 'United Kingdom',
    state: 'displayed',
    name: 'United Kingdom',
  },
  {
    count: 56562,
    path: 'France',
    state: 'displayed',
    name: 'France',
  },
  {
    count: 45844,
    path: 'Spain',
    state: 'displayed',
    name: 'Spain',
  },
  {
    count: 40693,
    path: 'Australia',
    state: 'displayed',
    name: 'Australia',
  },
  {
    count: 33146,
    path: 'Italy',
    state: 'displayed',
    name: 'Italy',
  },
  {
    count: 30787,
    path: 'Canada',
    state: 'displayed',
    name: 'Canada',
  },
  {
    count: 20576,
    path: 'Germany',
    state: 'displayed',
    name: 'Germany',
  },
  {
    count: 20545,
    path: 'Denmark',
    state: 'displayed',
    name: 'Denmark',
  },
  {
    count: 15181,
    path: 'Netherlands',
    state: 'displayed',
    name: 'Netherlands',
  },
  {
    count: 7893,
    path: 'Austria',
    state: 'displayed',
    name: 'Austria',
  },
  {
    count: 7419,
    path: 'Belgium',
    state: 'displayed',
    name: 'Belgium',
  },
  {
    count: 6729,
    path: 'Ireland',
    state: 'displayed',
    name: 'Ireland',
  },
  {
    count: 6423,
    path: 'Hong Kong',
    state: 'displayed',
    name: 'Hong Kong',
  },
  {
    count: 5127,
    path: 'Greece',
    state: 'displayed',
    name: 'Greece',
  },
  {
    count: 2381,
    path: 'Switzerland',
    state: 'displayed',
    name: 'Switzerland',
  },
  {
    count: 51,
    path: 'China',
    state: 'displayed',
    name: 'China',
  },
  {
    count: 2,
    path: 'Mexico',
    state: 'displayed',
    name: 'Mexico',
  },
  {
    count: 2,
    path: 'Vatican City',
    state: 'displayed',
    name: 'Vatican City',
  },
  {
    count: 1,
    path: '0',
    state: 'displayed',
    name: '0',
  },
  {
    count: 1,
    path: 'Cuba',
    state: 'displayed',
    name: 'Cuba',
  },
  {
    count: 1,
    path: 'Uruguay',
    state: 'displayed',
    name: 'Uruguay',
  },
  {
    count: 1,
    path: 'Vanuatu',
    state: 'displayed',
    name: 'Vanuatu',
  },
];
